# Generated by Django 3.1.2 on 2020-11-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_chirp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='user',
        ),
    ]
