# Generated by Django 3.1.2 on 2020-11-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0004_chirp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.createuser'),
        ),
    ]
