# Generated by Django 3.1.2 on 2020-11-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201107_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='user',
        ),
    ]
