# Generated by Django 3.1.2 on 2020-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201107_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
