# Generated by Django 3.1.2 on 2020-10-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoot',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hoot',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
