# Generated by Django 3.1.2 on 2020-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201026_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoot',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
