# Generated by Django 3.1.2 on 2020-10-23 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_item',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 23, 1, 39, 2, 853991, tzinfo=utc)),
        ),
    ]
