# Generated by Django 3.2.dev20201020074905 on 2020-10-23 04:13

from django.db import migrations, models
import grocery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_task', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('gnumber', models.IntegerField(default=0, validators=[grocery.models.validate_range])),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
