# Generated by Django 3.1.2 on 2020-11-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0002_conversation_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default='harryPotter', max_length=25),
            preserve_default=False,
        ),
    ]
