# Generated by Django 3.1.2 on 2020-11-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0003_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
