# Generated by Django 3.1.2 on 2020-11-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0004_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='image',
        ),
        migrations.AddField(
            model_name='conversation',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
