# Generated by Django 3.1.2 on 2020-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0005_auto_20201124_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='file',
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
