# Generated by Django 3.1.2 on 2020-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0006_auto_20201124_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='voicefile',
            field=models.FileField(default='1', upload_to='voicefiles'),
            preserve_default=False,
        ),
    ]
