# Generated by Django 3.1.2 on 2020-10-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='code',
            field=models.URLField(max_length=250),
        ),
    ]
