# Generated by Django 3.1.2 on 2020-11-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshr', '0002_auto_20201030_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
