# Generated by Django 3.1.2 on 2020-11-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshr', '0003_shortenedurl_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
