# Generated by Django 3.1.2 on 2020-10-23 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_auto_20201022_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_item',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 23, 1, 57, 40, 863863, tzinfo=utc)),
        ),
    ]
