# Generated by Django 3.1.2 on 2020-10-24 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0008_auto_20201022_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_item',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 24, 1, 20, 12, 604904, tzinfo=utc)),
        ),
    ]
