# Generated by Django 3.1.2 on 2020-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryList', '0002_auto_20201021_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='GroceryList',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
