# Generated by Django 3.1.2 on 2020-11-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
