# Generated by Django 3.2.dev20201020074905 on 2020-11-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('url', models.URLField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
