# Generated by Django 3.1.2 on 2020-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
